### ISSUE TITLE
[Bug] everything is working well, but i face a playback problem

### ISSUE THREAD

**Issue by ericvlog** [LimeDrive/stream-fusion#57]
It’s strange, but when I watch movies on StreamFusion, I often fast forward if the movie doesn’t interest me. However, I sometimes get an HTTP_IO_ERROR, and then it won’t play anymore. I’ve tested other add-ons, and they don’t have this problem. It seems like this issue happens because I fast forward so frequently.

**Comment by LimeDrive** [comment]
Hi,

Probably due to the re-stream proxy, I will try to improve that with a buffer and retry by next week.

Anyway, I don't really support this option, as users should not set the API key/token from debrid services in the global environment variable, since it activates the re-proxy setting automatically. Users of StreamFusion, to have a proper stream link, must connect their own account on the debrid service directly in the user config page. Ensure that every single user has their own debrid account; that way, StreamFusion doesn't proxy the link for re-stream and sends the debrid link directly from the service to Stremio, which is much more proper.

As I warned in the docs, debrid services are really cheap, so we must respect the service and their ToS.

**Comment by ericvlog** [comment]
> Hi,
> 
> Probably due to the re-stream proxy, I will try to improve that with a buffer and retry by next week.
> 
> Anyway, I don't really support this option, as users should not set the API key/token from debrid services in the global environment variable, since it activates the re-proxy setting automatically. Users of StreamFusion, to have a proper stream link, must connect their own account on the debrid service directly in the user config page. Ensure that every single user has their own debrid account; that way, StreamFusion doesn't proxy the link for re-stream and sends the debrid link directly from the service to Stremio, which is much more proper.
> 
> As I warned in the docs, debrid services are really cheap, so we must respect the service and their ToS.

Yup, fair enough if we just pay a tiny amount,if every 1 uses a proxy like warp then no longer soon debrid services will impose more aggressive rules.

So I just waited for your fix ya.

**Comment by LimeDrive** [comment]
I add a buffer of 1 MB by default and buffer size can be set with : 
`PROXY_BUFFER_SIZE`  = must be in bytes ( so 1MB = 1024 * 1024 )

Close cause : 
**users should not set the API key/token from debrid services in the global environment variable**
